In [1]:
import pandas as pd
from simpledbf import Dbf5
import numpy as np
import geopandas as gpd
import os

In [25]:
awc_SG = []
awc_HD = []
for i in range (347):
    SG_awc_out = "D:\\Tara_Fall_2019\\dosso_index\\SG_awc" + str(i) + ".shp"
    HWSD_awc_out = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_awc" + str(i) + ".shp"
    if os.path.exists(SG_awc_out):
        shp_SG = gpd.read_file(SG_awc_out)
        awc_SG.append(len(shp_SG[shp_SG['awc_bool'] == 1]))
    if os.path.exists(HWSD_awc_out):
        shp_HWSD = gpd.read_file(HWSD_awc_out)
        awc_HD.append(len(shp_HWSD[shp_HWSD['awc_bool'] == 1]))
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346

In [35]:
ero_SG = []
ero_HD = []
for i in range (347):
    SG_ero_na_out = "D:\\Tara_Fall_2019\\dosso_index\\SG_ero_na" + str(i) + ".shp"
    HWSD_ero_na_out = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_ero_na" + str(i) + ".shp"
    if os.path.exists(SG_ero_na_out):
        shp_SG = gpd.read_file(SG_ero_na_out)
        ero_SG.append(len(shp_SG[shp_SG['erosion_bo'] == 1]))
    if os.path.exists(HWSD_ero_na_out):
        shp_HWSD = gpd.read_file(HWSD_ero_na_out)
        ero_HD.append(len(shp_HWSD[shp_HWSD['erosion_bo'] == 1]))
    print (i, len(shp_SG[shp_SG['erosion_bo'] == 1]), len(shp_HWSD[shp_HWSD['erosion_bo'] == 1]))

0 135338 3867
1 1124 198
2 254762 17269
3 86403 2666
4 57463 4330
5 56755 975
6 36539 81
7 57751 1602
8 46042 168
9 86214 11535

KeyboardInterrupt:

In [31]:
sum(awc_SG)

172119279

In [6]:
 for i in range(330,347):
        print (i)

330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346

In [7]:

#run a loop to create new shapefiles with geolocation and lcc results 
for i in range(331,347):
    #import shapefiles to pull geolocation and csv files of results to link with 
    SG_results = "D:\\Tara_Fall_2019\\dosso_index\\LCC_SG_dosso_fullresults_" + str(i)
    shape_SG = "D:\\Tara_Fall_2019\\dosso_index\\base_SG0_slope" + str(i) + ".shp"

    HWSD_results = "D:\\Tara_Fall_2019\\dosso_index\\LCC_HWSD_dosso_fullresults_" + str(i)
    shape_HWSD = "D:\\Tara_Fall_2019\\dosso_index\\base_HWSD_slope" + str(i) + ".shp"
   
    #read in soilgrids files, remove any entries where data is missing 
    df_SG = pd.read_csv(SG_results)
    df_SG_full = df_SG.dropna()


    #df_SG["texture_bool_na"]= df_SG["limitation_noawc"].str.contains('t').astype(int) 
    df_SG_awc = df_SG['awc_total']

    
    shp_SG = gpd.read_file(shape_SG)
    shp_SG_full = shp_SG[shp_SG['sand'] != 0]
    
    #read in HWSD files, remove any entries where data is missing 
    df_HWSD = pd.read_csv(HWSD_results)
    df_HWSD_full = df_HWSD[df_HWSD['T_AWC'] != 0]


    #df_HWSD["texture_bool_na"]= df_HWSD["limitation_noawc"].str.contains('t').astype(int)
    df_HWSD['awc_total'] = df_HWSD['T_AWC'] + df_HWSD['S_AWC']

    
    shp_HWSD = gpd.read_file(shape_HWSD)
    shp_HWSD_full = shp_HWSD[shp_HWSD['OBJECTID'] != 0]
    
    #pull out columns to merge of LCC final and LCC without AWC
    SG_full_geo = shp_SG_full[['geometry']]
    HWSD_full_geo = shp_HWSD_full[['geometry']] 
    
#     SG_LCC = df_SG_full['LCC_final']
#     HWSD_LCC = df_HWSD_full['LCC_final']
    
#     SG_LCC_no = df_SG_full['LCC_final_noawc']
#     HWSD_LCC_no = df_HWSD_full['LCC_final_noawc']

#     SG_LCC_no = df_SG_full['LCC_final_noawc']
#     HWSD_LCC_no = df_HWSD_full['LCC_final_noawc']

    #pull out the column of limitations 
    

#     SG_tex_na = df_SG["texture_bool_na"]
#     HWSD_tex_na =df_HWSD["texture_bool_na"]
    df_HWSD_awc = df_HWSD['awc_total']
    
    #merge shapefiles with results
#     shp_SG_results = pd.concat([SG_full_geo, SG_LCC], axis = 1)
#     shp_SG_results_no = pd.concat([SG_full_geo, SG_LCC_no], axis = 1)

#     shp_SG_tex_na = pd.concat([SG_full_geo, SG_tex_na], axis = 1)
#     shp_HWSD_tex_na = pd.concat([HWSD_full_geo, HWSD_tex_na], axis = 1)

    shp_SG_awc = pd.concat([SG_full_geo, df_SG_awc], axis = 1)
    shp_HWSD_awc = pd.concat([HWSD_full_geo, df_HWSD_awc], axis = 1)

    
    #output to new shapefiles
#     SG_output = "D:\\Tara_Fall_2019\\dosso_index\\SG_LCC_geo" + str(i) + ".shp"
#     SG_no_output = "D:\\Tara_Fall_2019\\dosso_index\\SG_LCCnoA_geo" + str(i) + ".shp"
#     HWSD_output = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_LCC_geo" + str(i) + ".shp"
#     HWSD_no_output = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_LCCnoA_geo" + str(i) + ".shp"
    SG_awc_out = "D:\\Tara_Fall_2019\\dosso_index\\SG_awc" + str(i) + ".shp"
    HWSD_awc_out = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_awc" + str(i) + ".shp"


    if len(df_SG_full) > 0:
        shp_SG_awc.to_file(SG_awc_out)
        shp_HWSD_awc.to_file(HWSD_awc_out)

    print ("file done " + str(i))
#         shp_SG_results.to_file(SG_output)
#         shp_SG_results_no.to_file(SG_no_output)
#         shp_HWSD_results.to_file(HWSD_output)
#         shp_HWSD_results_no.to_file(HWSD_no_output)

file done 331
file done 332
file done 333
file done 334
file done 335
file done 336
file done 337
file done 338
file done 339
file done 340
file done 341
file done 342
file done 343
file done 344
file done 345
file done 346

In [3]:
df1 = pd.read_csv("C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\LCC_SG_dosso_fullresults_239")
df2 = pd.read_csv("C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\LCC_HWSD_dosso_fullresults_239")
join_data = "D:\Tara_Fall_2019\dosso_index\\HWSd_dosso_la.dbf"
join_dbf = Dbf5(join_data)
df_join = join_dbf.to_dataframe()

og1 = "D:\\Tara_Fall_2019\\dosso_index\\base_SG0_slope239.dbf" 
shp = gpd.read_file("D:\\Tara_Fall_2019\\dosso_index\\base_HWSD_slope239.shp")
og2 = "D:\\Tara_Fall_2019\\dosso_index\\base_HWSD_slope239.dbf" 
dbf01 = Dbf5(og1)
dbf02 = Dbf5(og2)
raw1 = dbf01.to_dataframe()
raw20 = dbf02.to_dataframe()

raw2 = raw20.merge(df_join, on='OBJECTID', how="left")

In [6]:
shp2 = gpd.read_file("D:\\Tara_Fall_2019\\dosso_index\\base_SG0_slope239.shp")

In [42]:
#run a loop to create new shapefiles with geolocation and lcc results 
for i in range(347):
    #import shapefiles to pull geolocation and csv files of results to link with 
    SG_results = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\LCC_SG_dosso_fullresults_" + str(i)
    shape_SG = "D:\\Tara_Fall_2019\\dosso_index\\base_SG0_slope" + str(i) + ".shp"

    HWSD_results = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\LCC_HWSD_dosso_fullresults_" + str(i)
    shape_HWSD = "D:\\Tara_Fall_2019\\dosso_index\\base_HWSD_slope" + str(i) + ".shp"
   
    #read in soilgrids files, remove any entries where data is missing 
    df_SG = pd.read_csv(SG_results)
    df_SG_full = df_SG.dropna()

    df_SG["texture_bool_na"]= df_SG["limitation_noawc"].str.contains('t').astype(int) 
    df_SG["erosion_bool_na"]= df_SG["limitation_noawc"].str.contains('e').astype(int) 
    df_SG["texture_bool"]= df_SG["limitation"].str.contains('t').astype(int) 
    df_SG["erosion_bool"]= df_SG["limitation"].str.contains('e').astype(int)
    df_SG["awc_bool"]= df_SG["limitation"].str.contains('a').astype(int)

    
    shp_SG = gpd.read_file(shape_SG)
    shp_SG_full = shp_SG[shp_SG['sand'] != 0]
    
    #read in HWSD files, remove any entries where data is missing 
    df_HWSD = pd.read_csv(HWSD_results)
    df_HWSD_full = df_HWSD[df_HWSD['T_AWC'] != 0]

    df_HWSD["texture_bool_na"]= df_HWSD["limitation_noawc"].str.contains('t').astype(int) 
    df_HWSD["erosion_bool_na"]= df_HWSD["limitation_noawc"].str.contains('e').astype(int) 
    df_HWSD["texture_bool"]= df_HWSD["limitation"].str.contains('t').astype(int) 
    df_HWSD["erosion_bool"]= df_HWSD["limitation"].str.contains('e').astype(int)
    df_HWSD["awc_bool"]= df_HWSD["limitation"].str.contains('a').astype(int)
    
    shp_HWSD = gpd.read_file(shape_HWSD)
    shp_HWSD_full = shp_HWSD[shp_HWSD['OBJECTID'] != 0]
    
    #pull out columns to merge of LCC final and LCC without AWC
    SG_full_geo = shp_SG_full[['geometry']]
    HWSD_full_geo = shp_HWSD_full[['geometry']] 
    
#     SG_LCC = df_SG_full['LCC_final']
#     HWSD_LCC = df_HWSD_full['LCC_final']
    
#     SG_LCC_no = df_SG_full['LCC_final_noawc']
#     HWSD_LCC_no = df_HWSD_full['LCC_final_noawc']

    #pull out the column of limitations 
    SG_tex_na = df_SG["texture_bool_na"]
    SG_ero_na = df_SG["erosion_bool_na"]
    SG_tex = df_SG["texture_bool"]
    SG_ero = df_SG["erosion_bool"]
    SG_awc = df_SG["awc_bool"]
    
    HWSD_tex_na =df_HWSD["texture_bool_na"]
    HWSD_ero_na =df_HWSD["erosion_bool_na"]
    HWSD_tex =df_HWSD["texture_bool"]
    HWSD_ero =df_HWSD["erosion_bool"]
    HWSD_awc =df_HWSD["awc_bool"]
    
    #merge shapefiles with results
#     shp_SG_results = pd.concat([SG_full_geo, SG_LCC], axis = 1)
#     shp_SG_results_no = pd.concat([SG_full_geo, SG_LCC_no], axis = 1)
    shp_SG_tex_na = pd.concat([SG_full_geo, SG_tex_na], axis = 1)
    shp_SG_ero_na = pd.concat([SG_full_geo, SG_ero_na], axis = 1)
    shp_SG_tex = pd.concat([SG_full_geo, SG_tex], axis = 1)
    shp_SG_ero = pd.concat([SG_full_geo, SG_ero], axis = 1)
    shp_SG_awc = pd.concat([SG_full_geo, SG_awc], axis = 1)    
#     shp_HWSD_results = pd.concat([HWSD_full_geo, HWSD_LCC], axis = 1)
#     shp_HWSD_results_no = pd.concat([HWSD_full_geo, HWSD_LCC_no], axis = 1)
    shp_HWSD_tex_na = pd.concat([HWSD_full_geo, HWSD_tex_na], axis = 1)
    shp_HWSD_ero_na = pd.concat([HWSD_full_geo, HWSD_ero_na], axis = 1)
    shp_HWSD_tex = pd.concat([HWSD_full_geo, HWSD_tex], axis = 1)
    shp_HWSD_ero = pd.concat([HWSD_full_geo, HWSD_ero], axis = 1)
    shp_HWSD_awc = pd.concat([HWSD_full_geo, HWSD_awc], axis = 1)
    
    #output to new shapefiles
#     SG_output = "D:\\Tara_Fall_2019\\dosso_index\\SG_LCC_geo" + str(i) + ".shp"
#     SG_no_output = "D:\\Tara_Fall_2019\\dosso_index\\SG_LCCnoA_geo" + str(i) + ".shp"
#     HWSD_output = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_LCC_geo" + str(i) + ".shp"
#     HWSD_no_output = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_LCCnoA_geo" + str(i) + ".shp"
    SG_tex_na_out = "D:\\Tara_Fall_2019\\dosso_index\\SG_tex_na" + str(i) + ".shp"
    SG_ero_na_out = "D:\\Tara_Fall_2019\\dosso_index\\SG_ero_na" + str(i) + ".shp"
    SG_tex_out = "D:\\Tara_Fall_2019\\dosso_index\\SG_tex" + str(i) + ".shp"
    SG_ero_out =  "D:\\Tara_Fall_2019\\dosso_index\\SG_ero" + str(i) + ".shp"
    SG_awc_out = "D:\\Tara_Fall_2019\\dosso_index\\SG_awc" + str(i) + ".shp"
    
    HWSD_tex_na_out = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_tex_na" + str(i) + ".shp"
    HWSD_ero_na_out = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_ero_na" + str(i) + ".shp"
    HWSD_tex_out = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_tex" + str(i) + ".shp"
    HWSD_ero_out =  "D:\\Tara_Fall_2019\\dosso_index\\HWSD_ero" + str(i) + ".shp"
    HWSD_awc_out = "D:\\Tara_Fall_2019\\dosso_index\\HWSD_awc" + str(i) + ".shp"

    if len(df_SG_full) > 0:
        shp_SG_tex_na.to_file(SG_tex_na_out)
        shp_SG_ero_na.to_file(SG_ero_na_out)
        shp_SG_tex.to_file(SG_tex_out)
        shp_SG_ero.to_file(SG_ero_out)
        shp_SG_awc.to_file(SG_awc_out)
        shp_HWSD_tex_na.to_file(HWSD_tex_na_out)
        shp_HWSD_ero_na.to_file(HWSD_ero_na_out)
        shp_HWSD_tex.to_file(HWSD_tex_out)
        shp_HWSD_ero.to_file(HWSD_ero_out)
        shp_HWSD_awc.to_file(HWSD_awc_out)
    print ("file done " + str(i))
#         shp_SG_results.to_file(SG_output)
#         shp_SG_results_no.to_file(SG_no_output)
#         shp_HWSD_results.to_file(HWSD_output)
#         shp_HWSD_results_no.to_file(HWSD_no_output)

                                                 geometry
0       POLYGON ((2650.535 137601.006, 2638.035 137601...
1       POLYGON ((3063.035 138551.006, 3075.535 138551...
2       POLYGON ((2088.035 137972.486, 2088.035 137976...
3       POLYGON ((2013.035 138601.006, 2000.535 138601...
4       POLYGON ((2150.535 138076.006, 2150.535 138088...
5       POLYGON ((2275.535 138126.006, 2263.035 138126...
6       POLYGON ((2825.535 137501.006, 2825.535 137513...
7       POLYGON ((1838.035 138376.006, 1825.535 138376...
8       POLYGON ((2988.035 137951.006, 2975.535 137951...
9       POLYGON ((2663.035 137913.506, 2663.035 137926...
10      POLYGON ((2950.535 137851.006, 2938.035 137851...
11      POLYGON ((2600.535 137876.006, 2588.035 137876...
12      POLYGON ((3000.535 137513.506, 2988.035 137513...
13      POLYGON ((2925.535 137563.506, 2913.035 137563...
14      POLYGON ((2550.535 137588.506, 2538.035 137588...
15      POLYGON ((2538.035 137863.506, 2525.535 137863...
16      POLYGON ((2138.035 137951.006, 2138.035 137938...
17      POLYGON ((1888.035 139438.506, 1875.535 139438...
18      POLYGON ((2500.535 137751.006, 2488.035 137751...
19      POLYGON ((2513.035 138326.006, 2513.035 138338...
20      POLYGON ((2925.535 137588.506, 2913.035 137588...
21      POLYGON ((2513.035 137763.506, 2500.535 137763...
22      POLYGON ((3100.535 137638.506, 3088.035 137638...
23      POLYGON ((3050.535 138013.506, 3038.035 138013...
24      POLYGON ((2538.035 138013.506, 2525.535 138013...
25      POLYGON ((2525.535 137551.006, 2513.035 137551...
26      POLYGON ((2963.035 138788.506, 2950.535 138788...
27      POLYGON ((1800.535 138376.006, 1813.035 138376...
28      POLYGON ((2963.035 137751.006, 2950.535 137751...
29      POLYGON ((1775.535 140763.506, 1763.035 140763...
...                                                   ...
161952  POLYGON ((3038.035 137163.506, 3025.535 137163...
161953  POLYGON ((2750.535 137213.506, 2738.035 137213...
161954  POLYGON ((2863.035 137263.506, 2850.535 137263...
161955  POLYGON ((2850.535 137451.006, 2838.035 137451...
161956  POLYGON ((2700.535 137451.006, 2688.035 137451...
161957  POLYGON ((2825.535 137138.506, 2825.535 137151...
161958  POLYGON ((2536.168 137363.506, 2538.035 137363...
161959  POLYGON ((2975.535 137288.506, 2963.035 137288...
161960  POLYGON ((2800.535 137163.506, 2788.035 137163...
161961  POLYGON ((3088.035 137351.006, 3075.535 137351...
161962  POLYGON ((2913.035 137426.006, 2900.535 137426...
161963  POLYGON ((2950.535 137476.006, 2938.035 137476...
161964  POLYGON ((3075.535 137351.006, 3063.035 137351...
161965  POLYGON ((2838.035 137301.006, 2825.535 137301...
161966  POLYGON ((3113.035 137488.506, 3100.535 137488...
161967  POLYGON ((2663.035 137401.006, 2650.535 137401...
161968  POLYGON ((2588.035 137301.006, 2588.035 137293...
161969  POLYGON ((2600.535 137413.506, 2588.035 137413...
161970  POLYGON ((3113.035 137313.506, 3100.535 137313...
161971  POLYGON ((2975.535 137013.506, 2963.035 137013...
161972  POLYGON ((3075.535 137038.506, 3063.035 137038...
161973  POLYGON ((3125.535 137351.006, 3113.035 137351...
161974  POLYGON ((2925.535 137151.006, 2913.035 137151...
161975  POLYGON ((2725.535 137376.006, 2713.035 137376...
161976  POLYGON ((2575.535 137338.506, 2563.035 137338...
161977  POLYGON ((2963.035 137363.506, 2950.535 137363...
161978  POLYGON ((2963.035 137338.506, 2950.535 137338...
161979  POLYGON ((2850.535 137013.506, 2863.035 137013...
161980  POLYGON ((2600.535 137501.006, 2588.035 137501...
161981  POLYGON ((2750.535 137288.506, 2738.035 137288...

[161982 rows x 1 columns]

In [38]:
# geodataframe has to be on the left of the dataframe for the merge output to be a geodataframe 
shp_results = pd.concat([shp, piece], axis=1)
print (type(shp_results))

<class 'geopandas.geodataframe.GeoDataFrame'>

In [84]:
shp_results.to_file("C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\0test.shp")

In [87]:
arcpy.PolygonToRaster_conversion("C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\0test.shp", "LCC_final", 
                                 "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\0test.tif", 12.5)

NameError: name 'arcpy' is not defined

In [24]:
raw2.columns

Index(['Join_Count', 'TARGET_FID', 'Join_Cou_1', 'TARGET_F_1', 'OBJECTID',
       'ID', 'GRIDCODE', 'FID_1', 'Id', 'gridcode', 'CompID', 'mukey',
       'MU_GLOBAL', 'MU_SOURCE1', 'MU_SOURCE2', 'ISSOIL', 'SHARE', 'SEQ',
       'SU_SYM74', 'SU_CODE74', 'SU_SYM85', 'SU_CODE85', 'SU_SYM90',
       'SU_CODE90', 'T_TEXTURE', 'DRAINAGE', 'REF_DEPTH', 'AWC_CLASS',
       'PHASE1', 'PHASE2', 'ROOTS', 'IL', 'SWR', 'ADD_PROP', 'T_GRAVEL',
       'T_SAND', 'T_SILT', 'T_CLAY', 'T_USDA_TEX', 'T_REF_BULK', 'T_BULK_DEN',
       'T_OC', 'T_PH_H2O', 'T_CEC_CLAY', 'T_CEC_SOIL', 'T_BS', 'T_TEB',
       'T_CACO3', 'T_CASO4', 'T_ESP', 'T_ECE', 'S_GRAVEL', 'S_SAND', 'S_SILT',
       'S_CLAY', 'S_USDA_TEX', 'S_REF_BULK', 'S_BULK_DEN', 'S_OC', 'S_PH_H2O',
       'S_CEC_CLAY', 'S_CEC_SOIL', 'S_BS', 'S_TEB', 'S_CACO3', 'S_CASO4',
       'S_ESP', 'S_ECE', 'FAO_Year', 'FAO_SU', 'FAO_Value', 'FAO74_CD',
       'FAO74_SU', 'FAO90_CD', 'FAO90_SU', 'XLOG', 'YLAT', 'ISO_CODE',
       'CNTRY_NAME', 'Soil_ID'],
      dtype='object')

In [43]:
len(raw1)

161982

In [44]:
len(df1)

161982

In [45]:
len(raw2)

161982

In [46]:
len(df2)

161982

In [55]:
df1['surface_texture'].value_counts()

sandy loam         39654
sandy clay loam    39108
Name: surface_texture, dtype: int64

In [52]:
raw1

,Join_Count,TARGET_FID,bulk_dens,cec,clay,course_fra,silt,sand,ph,org_c_cont,gridcode
0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,8,1,1435.0,11.0,28.0,0.0,21.0,52.0,62.0,104.0,18112
2,4,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8102
3,8,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,89848
4,9,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8102
5,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22906
6,4,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8102
7,6,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8102
8,6,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25606
9,1,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
10,7,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24293
11,1,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12,9,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8102
13,7,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33371
14,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
15,1,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
16,7,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18112
17,1,17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
18,1,18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
19,1,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
20,6,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36188
21,1,21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
22,4,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8102
23,9,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43551
24,1,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
25,6,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18112
26,2,26,1435.0,11.0,28.0,0.0,21.0,52.0,62.0,104.0,22906
27,5,27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18112
28,4,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18112
29,8,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25606
...,...,...,...,...,...,...,...,...,...,...,...
161952,4,161952,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54193
161953,1,161953,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161954,1,161954,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161955,1,161955,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161956,1,161956,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161957,1,161957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161958,3,161958,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72091
161959,8,161959,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24293
161960,1,161960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161961,8,161961,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33371
161962,2,161962,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18112
161963,8,161963,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22906
161964,9,161964,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40446
161965,1,161965,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161966,6,161966,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25606
161967,1,161967,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161968,3,161968,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24293
161969,1,161969,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161970,8,161970,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18112
161971,1,161971,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161972,7,161972,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24293
161973,5,161973,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25606
161974,1,161974,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161975,1,161975,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161976,8,161976,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51742
161977,7,161977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8102
161978,8,161978,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18112
161979,1,161979,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161980,1,161980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
161981,1,161981,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [33]:
len(raw2[raw2['T_SAND']==0])

0

In [31]:
raw2

,Join_Count,TARGET_FID,Join_Cou_1,TARGET_F_1,OBJECTID,ID,GRIDCODE,FID_1,Id,gridcode,...,FAO_Value,FAO74_CD,FAO74_SU,FAO90_CD,FAO90_SU,XLOG,YLAT,ISO_CODE,CNTRY_NAME,Soil_ID
0,1,0,3,0,267826,338944,29189,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
1,1,1,4,1,267826,354630,25606,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
2,1,2,4,2,267826,345015,24293,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
3,1,3,2,3,267826,342923,18112,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
4,1,4,2,4,267826,346090,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
5,1,5,4,5,267826,339903,22906,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
6,1,6,4,6,267826,331325,65046,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
7,1,7,4,7,267826,364702,0,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
8,1,8,2,8,267826,339688,45739,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
9,1,9,3,9,267826,334825,18112,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
10,1,10,4,10,267826,361336,25606,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
11,1,11,4,11,267826,356784,29189,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
12,1,12,4,12,267826,365989,40446,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
13,1,13,1,13,267826,343168,0,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
14,1,14,4,14,267826,345443,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
15,1,15,1,15,267826,356937,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
16,1,16,3,16,267826,304990,18112,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
17,1,17,4,17,267826,227302,61472,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
18,1,18,1,18,267826,355931,25606,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
19,1,19,3,19,268691,338911,18112,236124,268691,1204,...,Eutric Gleysols,2,Ge,0,NaN,4.08359,12.0017,NG,Nigeria,236125
20,1,20,4,20,267826,307628,22906,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
21,1,21,4,21,267826,345627,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
22,1,22,4,22,267826,347224,29189,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
23,1,23,4,23,267826,337942,22906,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
24,1,24,3,24,267826,362164,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
25,1,25,4,25,267826,344145,22906,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
26,1,26,2,26,267826,338629,18112,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
27,1,27,3,27,267826,359053,49166,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
28,1,28,3,28,267826,356943,36188,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
29,1,29,1,29,267826,340631,0,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599666,1,599666,1,599666,267826,383817,22906,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599667,1,599667,4,599667,267826,378132,24293,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599668,1,599668,4,599668,267826,376458,18112,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599669,1,599669,4,599669,267826,372459,45739,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599670,1,599670,3,599670,267826,373163,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599671,1,599671,4,599671,267826,373061,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599672,1,599672,4,599672,267826,374429,33371,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599673,1,599673,4,599673,267826,377750,32376,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599674,1,599674,2,599674,267826,383807,40446,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599675,1,599675,1,599675,267826,383711,25606,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599676,1,599676,3,599676,267826,376344,33371,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599677,1,599677,1,599677,267826,367041,0,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599678,1,599678,4,599678,267826,381202,25606,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599679,1,599679,4,599679,267826,377453,24293,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599680,1,599680,3,599680,267826,382779,18112,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599681,1,599681,2,599681,267826,383947,61472,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599682,1,599682,4,599682,267826,378932,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599683,1,599683,4,599683,267826,374979,33371,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599684,1,599684,2,599684,267826,372017,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599685,1,599685,4,599685,267826,380817,33371,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599686,1,599686,3,599686,267826,370489,25606,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599687,1,599687,4,599687,267826,369275,51110,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599688,1,599688,1,599688,267826,370187,0,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599689,1,599689,4,599689,267826,378098,29189,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599690,1,599690,2,599690,267826,375624,25606,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599691,1,599691,4,599691,267826,373662,18112,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599692,1,599692,3,599692,267826,369950,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599693,1,599693,1,599693,267826,380725,22906,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599694,1,599694,4,599694,267826,374174,8102,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369
599695,1,599695,2,599695,267826,383619,32376,235368,267826,1700,...,Eutric Regosols,10,Re,0,NaN,3.79988,12.2363,NG,Nigeria,235369